# Generated by Django 2.2 on 2019-05-30 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('phone', models.IntegerField(verbose_name='İrtibat Numarası')),
                ('IBAN', models.CharField(max_length=24)),
                ('about', models.TextField(max_length=500, verbose_name='Özet Bilgi')),
                ('abilities', models.TextField(max_length=300, verbose_name='Yetenekler')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
