# Generated by Django 2.2 on 2019-05-30 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('categories', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('localId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('localtion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('missionId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('finishDate', models.DateField()),
                ('title', models.CharField(max_length=30)),
                ('detail', models.TextField(max_length=400)),
                ('budget', models.FloatField()),
                ('isDone', models.BooleanField()),
                ('candidate', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Category')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Location')),
            ],
        ),
    ]
