# Generated by Django 2.2 on 2019-05-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='finishDate',
        ),
    ]
