# Generated by Django 2.2 on 2019-05-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_remove_mission_finishdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='isDone',
        ),
    ]
