# Generated by Django 2.2 on 2019-05-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_auto_20190531_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
