# Generated by Django 2.2 on 2019-05-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_auto_20190531_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
