# Generated by Django 2.2 on 2019-05-31 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0008_auto_20190531_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bütçe'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mission.Category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yayınlayan'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='detail',
            field=models.TextField(max_length=400, verbose_name='İlan Detayları'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mission.Location', verbose_name='Lokasyon'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=30, verbose_name='İlan Başlığı'),
        ),
    ]
