# Generated by Django 2.2 on 2019-05-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0009_auto_20190531_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-startDate']},
        ),
    ]
