# Generated by Django 2.2 on 2019-06-07 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Kategori')),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Lokasyon')),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('mission', models.TextField(max_length=500, verbose_name='Görev Detayları')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlandığı Tarih')),
                ('budget', models.FloatField(blank=True, default=None, null=True, verbose_name='Bütçe')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Category', verbose_name='Kategori')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yayınlayan')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.Location', verbose_name='Lokasyon')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
